### ISSUE TITLE
Add call to contribute when only default 360 degree view link is available

### ISSUE THREAD

**Issue by mmmatthew** [mmmatthew/water-fountains.org#137]
2\. if the "ground level 360 degree view" is empty, always put a "plus" suggesting the users to "curate" a proper link as quite some instantview-links go nowhere
    (https://beta.water-fountains.org/zurich?lang=de&queryType=byId&database=wikidata&idval=Q27229898
    or )

Originally listed in #121

**Comment by ralfhauser** [comment]
D.O. : ... has the undesirable side-effect of making users click twice - presumably instantstreetview want to advertise or avoid robots.
I wrote some Javascript code https://github.com/derrickoswald/CIMSpace/blob/master/js/streetview.js  to do this without the intermediate click. You can see it in operation with this movie https://send.firefox.com/download/bfa94fac12474f46/#2xdALxIqqexVlHs3UzdPPA. I think it works better than the instantstreetview solution because it orients the user to the location, but you should probably test it yourself.
It's packaged as an AMD module https://de.wikipedia.org/wiki/Asynchronous_module_definition, and uses the util.js file https://github.com/derrickoswald/CIMSpace/blob/master/js/util.js to make the CORS server request https://de.wikipedia.org/wiki/Cross-Origin_Resource_Sharing to Google, but you should be able to unpack it and either replace the util code - or copy it too.
Operation and integration should be fairly straight forward with urlFor (lon, lat) https://github.com/derrickoswald/CIMSpace/blob/a6be526c0ae38719c9828cadfc7c5ef6f2bab1fc/js/cimdetails.js#L225 giving you a Promise to return the Streetview URL for the wgs84 coordinates. It sometimes doesn't return something (where there is no Streetview data) so I would disable the Streetview button and only when it successfully returns (contains "pano" in the returned URL) you can put the link in your button and then enable it.

**Comment by derrickoswald** [comment]
Unsuccessfully tried to clone and run proximap:
`$ npm install

> node-sass@4.12.0 install <...>code/proximap/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-72_binding.node
Download complete..] - :
Binary saved to <...>code/proximap/node_modules/node-sass/vendor/linux-x64-72/binding.node
Caching binary to <...>.npm/node-sass/4.12.0/linux-x64-72_binding.node

> node-sass@4.12.0 postinstall <...>code/proximap/node_modules/node-sass
> node scripts/build.js

Binary found at <...>code/proximap/node_modules/node-sass/vendor/linux-x64-72/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1684 packages from 1737 contributors and audited 41325 packages in 26.885s
found 151 vulnerabilities (1 low, 150 high)
  run `npm audit fix` to fix them, or `npm audit` for details
$ npm run start

> proximap@1.0.0 prestart <...>code/proximap
> node git.version.js

version: '',
  revision: '94074f7',
  branch: 'develop',
  time: '2019-10-28 10:31:44 +0100'

> proximap@1.0.0 start <...>code/proximap
> ng serve

Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (<...>code/proximap/node_modules/tslib/tslib.js:64:9)
    at <...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:115:17
    at <...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:314:6
    at <...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:3:17
    at Object.<anonymous> (<...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at <...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:20:22
    at <...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:10:17
    at Object.<anonymous> (<...>code/proximap/node_modules/@angular/compiler-cli/src/ngtsc/indexer/src/transform.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proximap@1.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the proximap@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <...>.npm/_logs/2019-11-28T15_14_38_111Z-debug.log
`

**Comment by ralfhauser** [comment]
remaining issue: if multiple pano urls are stated in wikidata, the edit button appears multiple times even though always pointing to the same location

**Comment by mmmatthew** [comment]
@derrickoswald You need to install Angular CLI globally (as explained in the readme)
Run `npm install -g @angular/cli` to install Angular CLI globally

https://github.com/water-fountains/proximap/blob/develop/README.md
